# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
"""

from spotify_python_sdk.paths.me_audiobooks_contains.get import CheckUserSavedRaw
from spotify_python_sdk.paths.audiobooks_id.get import GetCatalogInfoRaw
from spotify_python_sdk.paths.audiobooks_id_chapters.get import GetChaptersByIdRaw
from spotify_python_sdk.paths.audiobooks.get import GetSeveralRaw
from spotify_python_sdk.paths.me_audiobooks.get import ListSavedRaw
from spotify_python_sdk.paths.me_audiobooks.delete import RemoveFromLibraryRaw
from spotify_python_sdk.paths.me_audiobooks.put import SaveCurrentUserLibraryRaw


class AudiobooksApiRaw(
    CheckUserSavedRaw,
    GetCatalogInfoRaw,
    GetChaptersByIdRaw,
    GetSeveralRaw,
    ListSavedRaw,
    RemoveFromLibraryRaw,
    SaveCurrentUserLibraryRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
