# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
"""

from spotify_python_sdk.paths.me_episodes_contains.get import CheckSavedEpisodes
from spotify_python_sdk.paths.shows_id_episodes.get import GetEpisodesById
from spotify_python_sdk.paths.episodes.get import GetSeveral
from spotify_python_sdk.paths.episodes_id.get import GetSingleById
from spotify_python_sdk.paths.me_episodes.get import GetUserSavedEpisodes
from spotify_python_sdk.paths.me_episodes.delete import RemoveFromLibrary
from spotify_python_sdk.paths.me_episodes.put import SaveCurrentUserLibrary
from spotify_python_sdk.apis.tags.episodes_api_raw import EpisodesApiRaw


class EpisodesApi(
    CheckSavedEpisodes,
    GetEpisodesById,
    GetSeveral,
    GetSingleById,
    GetUserSavedEpisodes,
    RemoveFromLibrary,
    SaveCurrentUserLibrary,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EpisodesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EpisodesApiRaw(api_client)
