# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
"""

from spotify_python_sdk.paths.me_following_contains.get import CheckFollowingArtistsUsersRaw
from spotify_python_sdk.paths.me_albums_contains.get import CheckSavedRaw
from spotify_python_sdk.paths.me_tracks_contains.get import CheckSaved0Raw
from spotify_python_sdk.paths.me_episodes_contains.get import CheckSavedEpisodesRaw
from spotify_python_sdk.paths.me_shows_contains.get import CheckSavedShowsRaw
from spotify_python_sdk.paths.me_audiobooks_contains.get import CheckUserSavedRaw
from spotify_python_sdk.paths.users_user_id_playlists.post import CreatePlaylistRaw
from spotify_python_sdk.paths.me_following.put import FollowArtistsOrUsersRaw
from spotify_python_sdk.paths.me_following.get import GetFollowedArtistsRaw
from spotify_python_sdk.paths.me_albums.get import GetSavedRaw
from spotify_python_sdk.paths.me_top_type.get import GetTopItemsRaw
from spotify_python_sdk.paths.me_playlists.get import GetUserPlaylistsRaw
from spotify_python_sdk.paths.me_tracks.get import GetUserSavedRaw
from spotify_python_sdk.paths.me_episodes.get import GetUserSavedEpisodesRaw
from spotify_python_sdk.paths.me_shows.get import GetUserSavedShowsRaw
from spotify_python_sdk.paths.me_audiobooks.get import ListSavedRaw
from spotify_python_sdk.paths.me_audiobooks.delete import RemoveFromLibraryRaw
from spotify_python_sdk.paths.me_tracks.delete import RemoveFromLibrary0Raw
from spotify_python_sdk.paths.me_episodes.delete import RemoveFromLibrary1Raw
from spotify_python_sdk.paths.me_albums.delete import RemoveSavedRaw
from spotify_python_sdk.paths.me_shows.delete import RemoveUserLibraryRaw
from spotify_python_sdk.paths.me_audiobooks.put import SaveCurrentUserLibraryRaw
from spotify_python_sdk.paths.me_albums.put import SaveCurrentUserLibrary0Raw
from spotify_python_sdk.paths.me_episodes.put import SaveCurrentUserLibrary1Raw
from spotify_python_sdk.paths.me_shows.put import SaveCurrentUserLibrary2Raw
from spotify_python_sdk.paths.me_tracks.put import SaveForCurrentUserRaw
from spotify_python_sdk.paths.me_following.delete import UnfollowArtistsUsersRaw
from spotify_python_sdk.paths.playlists_playlist_id.put import UpdateDetailsRaw


class LibraryApiRaw(
    CheckFollowingArtistsUsersRaw,
    CheckSavedRaw,
    CheckSaved0Raw,
    CheckSavedEpisodesRaw,
    CheckSavedShowsRaw,
    CheckUserSavedRaw,
    CreatePlaylistRaw,
    FollowArtistsOrUsersRaw,
    GetFollowedArtistsRaw,
    GetSavedRaw,
    GetTopItemsRaw,
    GetUserPlaylistsRaw,
    GetUserSavedRaw,
    GetUserSavedEpisodesRaw,
    GetUserSavedShowsRaw,
    ListSavedRaw,
    RemoveFromLibraryRaw,
    RemoveFromLibrary0Raw,
    RemoveFromLibrary1Raw,
    RemoveSavedRaw,
    RemoveUserLibraryRaw,
    SaveCurrentUserLibraryRaw,
    SaveCurrentUserLibrary0Raw,
    SaveCurrentUserLibrary1Raw,
    SaveCurrentUserLibrary2Raw,
    SaveForCurrentUserRaw,
    UnfollowArtistsUsersRaw,
    UpdateDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
