# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
"""

from spotify_python_sdk.paths.me_following_contains.get import CheckFollowingArtistsUsers
from spotify_python_sdk.paths.me_albums_contains.get import CheckSaved
from spotify_python_sdk.paths.me_tracks_contains.get import CheckSaved0
from spotify_python_sdk.paths.me_episodes_contains.get import CheckSavedEpisodes
from spotify_python_sdk.paths.me_shows_contains.get import CheckSavedShows
from spotify_python_sdk.paths.me_audiobooks_contains.get import CheckUserSaved
from spotify_python_sdk.paths.users_user_id_playlists.post import CreatePlaylist
from spotify_python_sdk.paths.me_following.put import FollowArtistsOrUsers
from spotify_python_sdk.paths.me_following.get import GetFollowedArtists
from spotify_python_sdk.paths.me_albums.get import GetSaved
from spotify_python_sdk.paths.me_top_type.get import GetTopItems
from spotify_python_sdk.paths.me_playlists.get import GetUserPlaylists
from spotify_python_sdk.paths.me_tracks.get import GetUserSaved
from spotify_python_sdk.paths.me_episodes.get import GetUserSavedEpisodes
from spotify_python_sdk.paths.me_shows.get import GetUserSavedShows
from spotify_python_sdk.paths.me_audiobooks.get import ListSaved
from spotify_python_sdk.paths.me_audiobooks.delete import RemoveFromLibrary
from spotify_python_sdk.paths.me_tracks.delete import RemoveFromLibrary0
from spotify_python_sdk.paths.me_episodes.delete import RemoveFromLibrary1
from spotify_python_sdk.paths.me_albums.delete import RemoveSaved
from spotify_python_sdk.paths.me_shows.delete import RemoveUserLibrary
from spotify_python_sdk.paths.me_audiobooks.put import SaveCurrentUserLibrary
from spotify_python_sdk.paths.me_albums.put import SaveCurrentUserLibrary0
from spotify_python_sdk.paths.me_episodes.put import SaveCurrentUserLibrary1
from spotify_python_sdk.paths.me_shows.put import SaveCurrentUserLibrary2
from spotify_python_sdk.paths.me_tracks.put import SaveForCurrentUser
from spotify_python_sdk.paths.me_following.delete import UnfollowArtistsUsers
from spotify_python_sdk.paths.playlists_playlist_id.put import UpdateDetails
from spotify_python_sdk.apis.tags.library_api_raw import LibraryApiRaw


class LibraryApi(
    CheckFollowingArtistsUsers,
    CheckSaved,
    CheckSaved0,
    CheckSavedEpisodes,
    CheckSavedShows,
    CheckUserSaved,
    CreatePlaylist,
    FollowArtistsOrUsers,
    GetFollowedArtists,
    GetSaved,
    GetTopItems,
    GetUserPlaylists,
    GetUserSaved,
    GetUserSavedEpisodes,
    GetUserSavedShows,
    ListSaved,
    RemoveFromLibrary,
    RemoveFromLibrary0,
    RemoveFromLibrary1,
    RemoveSaved,
    RemoveUserLibrary,
    SaveCurrentUserLibrary,
    SaveCurrentUserLibrary0,
    SaveCurrentUserLibrary1,
    SaveCurrentUserLibrary2,
    SaveForCurrentUser,
    UnfollowArtistsUsers,
    UpdateDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: LibraryApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = LibraryApiRaw(api_client)
