# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
"""

from spotify_python_sdk.paths.me_player_queue.post import AddItemToQueue
from spotify_python_sdk.paths.me_player_devices.get import GetAvailableDevices
from spotify_python_sdk.paths.me_player.get import GetCurrentPlaybackState
from spotify_python_sdk.paths.me_player_currently_playing.get import GetCurrentlyPlayingTrack
from spotify_python_sdk.paths.me_player_recently_played.get import GetRecentlyPlayedTracks
from spotify_python_sdk.paths.me_player_queue.get import GetUserQueue
from spotify_python_sdk.paths.me_player_pause.put import PausePlayback
from spotify_python_sdk.paths.me_player_seek.put import SeekToPosition
from spotify_python_sdk.paths.me_player_volume.put import SetPlaybackVolume
from spotify_python_sdk.paths.me_player_repeat.put import SetRepeatMode
from spotify_python_sdk.paths.me_player_next.post import SkipToNextTrack
from spotify_python_sdk.paths.me_player_previous.post import SkipToPreviousTrack
from spotify_python_sdk.paths.me_player_play.put import StartPlayback
from spotify_python_sdk.paths.me_player_shuffle.put import TogglePlaybackShuffle
from spotify_python_sdk.paths.me_player.put import TransferPlaybackToNewDevice
from spotify_python_sdk.apis.tags.player_api_raw import PlayerApiRaw


class PlayerApi(
    AddItemToQueue,
    GetAvailableDevices,
    GetCurrentPlaybackState,
    GetCurrentlyPlayingTrack,
    GetRecentlyPlayedTracks,
    GetUserQueue,
    PausePlayback,
    SeekToPosition,
    SetPlaybackVolume,
    SetRepeatMode,
    SkipToNextTrack,
    SkipToPreviousTrack,
    StartPlayback,
    TogglePlaybackShuffle,
    TransferPlaybackToNewDevice,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PlayerApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PlayerApiRaw(api_client)
