# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
"""

from spotify_python_sdk.paths.me_shows_contains.get import CheckSavedShows
from spotify_python_sdk.paths.shows_id_episodes.get import GetEpisodesById
from spotify_python_sdk.paths.shows_id.get import GetInformation
from spotify_python_sdk.paths.shows.get import GetMultipleShowsInfo
from spotify_python_sdk.paths.me_shows.get import GetUserSavedShows
from spotify_python_sdk.paths.me_shows.delete import RemoveUserLibrary
from spotify_python_sdk.paths.me_shows.put import SaveCurrentUserLibrary
from spotify_python_sdk.apis.tags.shows_api_raw import ShowsApiRaw


class ShowsApi(
    CheckSavedShows,
    GetEpisodesById,
    GetInformation,
    GetMultipleShowsInfo,
    GetUserSavedShows,
    RemoveUserLibrary,
    SaveCurrentUserLibrary,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ShowsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ShowsApiRaw(api_client)
