# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from spotify_python_sdk import schemas  # noqa: F401


class DisallowsObject(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            interrupting_playback = schemas.BoolSchema
            pausing = schemas.BoolSchema
            resuming = schemas.BoolSchema
            seeking = schemas.BoolSchema
            skipping_next = schemas.BoolSchema
            skipping_prev = schemas.BoolSchema
            toggling_repeat_context = schemas.BoolSchema
            toggling_shuffle = schemas.BoolSchema
            toggling_repeat_track = schemas.BoolSchema
            transferring_playback = schemas.BoolSchema
            __annotations__ = {
                "interrupting_playback": interrupting_playback,
                "pausing": pausing,
                "resuming": resuming,
                "seeking": seeking,
                "skipping_next": skipping_next,
                "skipping_prev": skipping_prev,
                "toggling_repeat_context": toggling_repeat_context,
                "toggling_shuffle": toggling_shuffle,
                "toggling_repeat_track": toggling_repeat_track,
                "transferring_playback": transferring_playback,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["interrupting_playback"]) -> MetaOapg.properties.interrupting_playback: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pausing"]) -> MetaOapg.properties.pausing: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resuming"]) -> MetaOapg.properties.resuming: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["seeking"]) -> MetaOapg.properties.seeking: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["skipping_next"]) -> MetaOapg.properties.skipping_next: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["skipping_prev"]) -> MetaOapg.properties.skipping_prev: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["toggling_repeat_context"]) -> MetaOapg.properties.toggling_repeat_context: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["toggling_shuffle"]) -> MetaOapg.properties.toggling_shuffle: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["toggling_repeat_track"]) -> MetaOapg.properties.toggling_repeat_track: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transferring_playback"]) -> MetaOapg.properties.transferring_playback: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["interrupting_playback", "pausing", "resuming", "seeking", "skipping_next", "skipping_prev", "toggling_repeat_context", "toggling_shuffle", "toggling_repeat_track", "transferring_playback", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["interrupting_playback"]) -> typing.Union[MetaOapg.properties.interrupting_playback, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pausing"]) -> typing.Union[MetaOapg.properties.pausing, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resuming"]) -> typing.Union[MetaOapg.properties.resuming, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["seeking"]) -> typing.Union[MetaOapg.properties.seeking, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["skipping_next"]) -> typing.Union[MetaOapg.properties.skipping_next, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["skipping_prev"]) -> typing.Union[MetaOapg.properties.skipping_prev, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["toggling_repeat_context"]) -> typing.Union[MetaOapg.properties.toggling_repeat_context, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["toggling_shuffle"]) -> typing.Union[MetaOapg.properties.toggling_shuffle, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["toggling_repeat_track"]) -> typing.Union[MetaOapg.properties.toggling_repeat_track, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transferring_playback"]) -> typing.Union[MetaOapg.properties.transferring_playback, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["interrupting_playback", "pausing", "resuming", "seeking", "skipping_next", "skipping_prev", "toggling_repeat_context", "toggling_shuffle", "toggling_repeat_track", "transferring_playback", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        interrupting_playback: typing.Union[MetaOapg.properties.interrupting_playback, bool, schemas.Unset] = schemas.unset,
        pausing: typing.Union[MetaOapg.properties.pausing, bool, schemas.Unset] = schemas.unset,
        resuming: typing.Union[MetaOapg.properties.resuming, bool, schemas.Unset] = schemas.unset,
        seeking: typing.Union[MetaOapg.properties.seeking, bool, schemas.Unset] = schemas.unset,
        skipping_next: typing.Union[MetaOapg.properties.skipping_next, bool, schemas.Unset] = schemas.unset,
        skipping_prev: typing.Union[MetaOapg.properties.skipping_prev, bool, schemas.Unset] = schemas.unset,
        toggling_repeat_context: typing.Union[MetaOapg.properties.toggling_repeat_context, bool, schemas.Unset] = schemas.unset,
        toggling_shuffle: typing.Union[MetaOapg.properties.toggling_shuffle, bool, schemas.Unset] = schemas.unset,
        toggling_repeat_track: typing.Union[MetaOapg.properties.toggling_repeat_track, bool, schemas.Unset] = schemas.unset,
        transferring_playback: typing.Union[MetaOapg.properties.transferring_playback, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DisallowsObject':
        return super().__new__(
            cls,
            *args,
            interrupting_playback=interrupting_playback,
            pausing=pausing,
            resuming=resuming,
            seeking=seeking,
            skipping_next=skipping_next,
            skipping_prev=skipping_prev,
            toggling_repeat_context=toggling_repeat_context,
            toggling_shuffle=toggling_shuffle,
            toggling_repeat_track=toggling_repeat_track,
            transferring_playback=transferring_playback,
            _configuration=_configuration,
            **kwargs,
        )
