# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from spotify_python_sdk import schemas  # noqa: F401


class PlaylistTrackObject(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            added_at = schemas.DateTimeSchema
        
            @staticmethod
            def added_by() -> typing.Type['PlaylistUserObject']:
                return PlaylistUserObject
            is_local = schemas.BoolSchema
            
            
            class track(
                schemas.ComposedSchema,
            ):
            
            
                class MetaOapg:
                    
                    @classmethod
                    @functools.lru_cache()
                    def one_of(cls):
                        # we need this here to make our import statements work
                        # we must store _composed_schemas in here so the code is only run
                        # when we invoke this method. If we kept this at the class
                        # level we would get an error because the class level
                        # code would be run when this module is imported, and these composed
                        # classes don't exist yet because their module has not finished
                        # loading
                        return [
                            TrackObject,
                            EpisodeObject,
                        ]
            
            
                def __new__(
                    cls,
                    *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'track':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            __annotations__ = {
                "added_at": added_at,
                "added_by": added_by,
                "is_local": is_local,
                "track": track,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["added_at"]) -> MetaOapg.properties.added_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["added_by"]) -> 'PlaylistUserObject': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_local"]) -> MetaOapg.properties.is_local: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["track"]) -> MetaOapg.properties.track: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["added_at", "added_by", "is_local", "track", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["added_at"]) -> typing.Union[MetaOapg.properties.added_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["added_by"]) -> typing.Union['PlaylistUserObject', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_local"]) -> typing.Union[MetaOapg.properties.is_local, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["track"]) -> typing.Union[MetaOapg.properties.track, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["added_at", "added_by", "is_local", "track", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        added_at: typing.Union[MetaOapg.properties.added_at, str, datetime, schemas.Unset] = schemas.unset,
        added_by: typing.Union['PlaylistUserObject', schemas.Unset] = schemas.unset,
        is_local: typing.Union[MetaOapg.properties.is_local, bool, schemas.Unset] = schemas.unset,
        track: typing.Union[MetaOapg.properties.track, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PlaylistTrackObject':
        return super().__new__(
            cls,
            *args,
            added_at=added_at,
            added_by=added_by,
            is_local=is_local,
            track=track,
            _configuration=_configuration,
            **kwargs,
        )

from spotify_python_sdk.model.episode_object import EpisodeObject
from spotify_python_sdk.model.playlist_user_object import PlaylistUserObject
from spotify_python_sdk.model.track_object import TrackObject
