# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from spotify_python_sdk import schemas  # noqa: F401


class PlayerTransferPlaybackToNewDeviceRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "device_ids",
        }
        
        class properties:
        
            @staticmethod
            def device_ids() -> typing.Type['PlayerTransferPlaybackToNewDeviceRequestDeviceIds']:
                return PlayerTransferPlaybackToNewDeviceRequestDeviceIds
            
            
            class play(
                schemas.DictSchema
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *args: typing.Union[dict, frozendict.frozendict, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'play':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            __annotations__ = {
                "device_ids": device_ids,
                "play": play,
            }
        additional_properties = schemas.AnyTypeSchema
    
    device_ids: 'PlayerTransferPlaybackToNewDeviceRequestDeviceIds'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["device_ids"]) -> 'PlayerTransferPlaybackToNewDeviceRequestDeviceIds': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["play"]) -> MetaOapg.properties.play: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> MetaOapg.additional_properties: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["device_ids"], typing_extensions.Literal["play"], str, ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["device_ids"]) -> 'PlayerTransferPlaybackToNewDeviceRequestDeviceIds': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["play"]) -> typing.Union[MetaOapg.properties.play, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[MetaOapg.additional_properties, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["device_ids"], typing_extensions.Literal["play"], str, ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        device_ids: 'PlayerTransferPlaybackToNewDeviceRequestDeviceIds',
        play: typing.Union[MetaOapg.properties.play, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    ) -> 'PlayerTransferPlaybackToNewDeviceRequest':
        return super().__new__(
            cls,
            *args,
            device_ids=device_ids,
            play=play,
            _configuration=_configuration,
            **kwargs,
        )

from spotify_python_sdk.model.player_transfer_playback_to_new_device_request_device_ids import PlayerTransferPlaybackToNewDeviceRequestDeviceIds
