# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from spotify_python_sdk import schemas  # noqa: F401


class SearchSpotifyCatalogInfoResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def tracks() -> typing.Type['PagingTrackObject']:
                return PagingTrackObject
        
            @staticmethod
            def artists() -> typing.Type['PagingArtistObject']:
                return PagingArtistObject
        
            @staticmethod
            def albums() -> typing.Type['PagingSimplifiedAlbumObject']:
                return PagingSimplifiedAlbumObject
        
            @staticmethod
            def playlists() -> typing.Type['PagingPlaylistObject']:
                return PagingPlaylistObject
        
            @staticmethod
            def shows() -> typing.Type['PagingSimplifiedShowObject']:
                return PagingSimplifiedShowObject
        
            @staticmethod
            def episodes() -> typing.Type['PagingSimplifiedEpisodeObject']:
                return PagingSimplifiedEpisodeObject
        
            @staticmethod
            def audiobooks() -> typing.Type['PagingSimplifiedAudiobookObject']:
                return PagingSimplifiedAudiobookObject
            __annotations__ = {
                "tracks": tracks,
                "artists": artists,
                "albums": albums,
                "playlists": playlists,
                "shows": shows,
                "episodes": episodes,
                "audiobooks": audiobooks,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tracks"]) -> 'PagingTrackObject': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["artists"]) -> 'PagingArtistObject': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["albums"]) -> 'PagingSimplifiedAlbumObject': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["playlists"]) -> 'PagingPlaylistObject': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shows"]) -> 'PagingSimplifiedShowObject': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["episodes"]) -> 'PagingSimplifiedEpisodeObject': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["audiobooks"]) -> 'PagingSimplifiedAudiobookObject': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["tracks", "artists", "albums", "playlists", "shows", "episodes", "audiobooks", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tracks"]) -> typing.Union['PagingTrackObject', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["artists"]) -> typing.Union['PagingArtistObject', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["albums"]) -> typing.Union['PagingSimplifiedAlbumObject', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["playlists"]) -> typing.Union['PagingPlaylistObject', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shows"]) -> typing.Union['PagingSimplifiedShowObject', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["episodes"]) -> typing.Union['PagingSimplifiedEpisodeObject', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["audiobooks"]) -> typing.Union['PagingSimplifiedAudiobookObject', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["tracks", "artists", "albums", "playlists", "shows", "episodes", "audiobooks", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        tracks: typing.Union['PagingTrackObject', schemas.Unset] = schemas.unset,
        artists: typing.Union['PagingArtistObject', schemas.Unset] = schemas.unset,
        albums: typing.Union['PagingSimplifiedAlbumObject', schemas.Unset] = schemas.unset,
        playlists: typing.Union['PagingPlaylistObject', schemas.Unset] = schemas.unset,
        shows: typing.Union['PagingSimplifiedShowObject', schemas.Unset] = schemas.unset,
        episodes: typing.Union['PagingSimplifiedEpisodeObject', schemas.Unset] = schemas.unset,
        audiobooks: typing.Union['PagingSimplifiedAudiobookObject', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SearchSpotifyCatalogInfoResponse':
        return super().__new__(
            cls,
            *args,
            tracks=tracks,
            artists=artists,
            albums=albums,
            playlists=playlists,
            shows=shows,
            episodes=episodes,
            audiobooks=audiobooks,
            _configuration=_configuration,
            **kwargs,
        )

from spotify_python_sdk.model.paging_artist_object import PagingArtistObject
from spotify_python_sdk.model.paging_playlist_object import PagingPlaylistObject
from spotify_python_sdk.model.paging_simplified_album_object import PagingSimplifiedAlbumObject
from spotify_python_sdk.model.paging_simplified_audiobook_object import PagingSimplifiedAudiobookObject
from spotify_python_sdk.model.paging_simplified_episode_object import PagingSimplifiedEpisodeObject
from spotify_python_sdk.model.paging_simplified_show_object import PagingSimplifiedShowObject
from spotify_python_sdk.model.paging_track_object import PagingTrackObject
