# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from spotify_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    ALBUMS_ID = "/albums/{id}"
    ALBUMS = "/albums"
    ALBUMS_ID_TRACKS = "/albums/{id}/tracks"
    ARTISTS_ID = "/artists/{id}"
    ARTISTS = "/artists"
    ARTISTS_ID_ALBUMS = "/artists/{id}/albums"
    ARTISTS_ID_TOPTRACKS = "/artists/{id}/top-tracks"
    ARTISTS_ID_RELATEDARTISTS = "/artists/{id}/related-artists"
    SHOWS_ID = "/shows/{id}"
    SHOWS = "/shows"
    SHOWS_ID_EPISODES = "/shows/{id}/episodes"
    EPISODES_ID = "/episodes/{id}"
    EPISODES = "/episodes"
    AUDIOBOOKS_ID = "/audiobooks/{id}"
    AUDIOBOOKS = "/audiobooks"
    AUDIOBOOKS_ID_CHAPTERS = "/audiobooks/{id}/chapters"
    ME_AUDIOBOOKS = "/me/audiobooks"
    ME_AUDIOBOOKS_CONTAINS = "/me/audiobooks/contains"
    CHAPTERS_ID = "/chapters/{id}"
    CHAPTERS = "/chapters"
    TRACKS_ID = "/tracks/{id}"
    TRACKS = "/tracks"
    SEARCH = "/search"
    ME = "/me"
    PLAYLISTS_PLAYLIST_ID = "/playlists/{playlist_id}"
    PLAYLISTS_PLAYLIST_ID_TRACKS = "/playlists/{playlist_id}/tracks"
    ME_PLAYLISTS = "/me/playlists"
    ME_ALBUMS = "/me/albums"
    ME_ALBUMS_CONTAINS = "/me/albums/contains"
    ME_TRACKS = "/me/tracks"
    ME_TRACKS_CONTAINS = "/me/tracks/contains"
    ME_EPISODES = "/me/episodes"
    ME_EPISODES_CONTAINS = "/me/episodes/contains"
    ME_SHOWS = "/me/shows"
    ME_SHOWS_CONTAINS = "/me/shows/contains"
    ME_TOP_TYPE = "/me/top/{type}"
    USERS_USER_ID = "/users/{user_id}"
    USERS_USER_ID_PLAYLISTS = "/users/{user_id}/playlists"
    PLAYLISTS_PLAYLIST_ID_FOLLOWERS = "/playlists/{playlist_id}/followers"
    BROWSE_FEATUREDPLAYLISTS = "/browse/featured-playlists"
    BROWSE_CATEGORIES = "/browse/categories"
    BROWSE_CATEGORIES_CATEGORY_ID = "/browse/categories/{category_id}"
    BROWSE_CATEGORIES_CATEGORY_ID_PLAYLISTS = "/browse/categories/{category_id}/playlists"
    PLAYLISTS_PLAYLIST_ID_IMAGES = "/playlists/{playlist_id}/images"
    BROWSE_NEWRELEASES = "/browse/new-releases"
    ME_FOLLOWING = "/me/following"
    ME_FOLLOWING_CONTAINS = "/me/following/contains"
    PLAYLISTS_PLAYLIST_ID_FOLLOWERS_CONTAINS = "/playlists/{playlist_id}/followers/contains"
    AUDIOFEATURES = "/audio-features"
    AUDIOFEATURES_ID = "/audio-features/{id}"
    AUDIOANALYSIS_ID = "/audio-analysis/{id}"
    RECOMMENDATIONS = "/recommendations"
    RECOMMENDATIONS_AVAILABLEGENRESEEDS = "/recommendations/available-genre-seeds"
    ME_PLAYER = "/me/player"
    ME_PLAYER_DEVICES = "/me/player/devices"
    ME_PLAYER_CURRENTLYPLAYING = "/me/player/currently-playing"
    ME_PLAYER_PLAY = "/me/player/play"
    ME_PLAYER_PAUSE = "/me/player/pause"
    ME_PLAYER_NEXT = "/me/player/next"
    ME_PLAYER_PREVIOUS = "/me/player/previous"
    ME_PLAYER_SEEK = "/me/player/seek"
    ME_PLAYER_REPEAT = "/me/player/repeat"
    ME_PLAYER_VOLUME = "/me/player/volume"
    ME_PLAYER_SHUFFLE = "/me/player/shuffle"
    ME_PLAYER_RECENTLYPLAYED = "/me/player/recently-played"
    ME_PLAYER_QUEUE = "/me/player/queue"
    MARKETS = "/markets"
